### ISSUE TITLE
When I installed the 0.4.1 version, I got the following error.

### ISSUE THREAD

**Issue by Shawn-Yuan-byte** [titan-data/ssh-remote#11]
## Expected Behavior

Successfully installed titan

## Actual Behavior

During the installation of titan, an exception occurred.

## Steps to Reproduce the Problem

Call the following command line
`TITAN_DEBUG=true titan install`

## Version

**root@DBForTitan:/#** uname -a
Linux DBForTitan 5.0.0-1027-azure #29~18.04.1-Ubuntu SMP Mon Nov 25 21:18:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**root@DBForTitan:/#** uname -r
5.0.0-1027-azure
**root@DBForTitan:/home/ubuntu#** titan --version
titan version 0.4.1

## Additional Information

**root@DBForTitan:/home/ubuntu#** titan --version
titan version 0.4.1
**root@DBForTitan:/home/ubuntu#** TITAN_DEBUG=true titan install
Initializing titan infrastructure ...
Dec 24, 2019 4:43:52 AM org.jline.utils.Log logr
WARNING: Unable to retrieve infocmp for type xterm
java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at org.jline.utils.InputStreamReader.<init>(InputStreamReader.java:135)
        at org.jline.utils.InfoCmp.loadDefaultInfoCmp(InfoCmp.java:608)
        at org.jline.utils.InfoCmp.lambda$static$3(InfoCmp.java:619)
        at org.jline.utils.InfoCmp.getLoadedInfoCmp(InfoCmp.java:557)
        at org.jline.utils.InfoCmp.getInfoCmp(InfoCmp.java:545)
        at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:187)
        at org.jline.terminal.impl.PosixSysTerminal.<init>(PosixSysTerminal.java:44)
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:374)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:259)
        at me.tongfei.progressbar.ProgressThread.<init>(ProgressThread.java:56)
        at me.tongfei.progressbar.ProgressBar.<init>(ProgressBar.java:91)
        at me.tongfei.progressbar.ProgressBarBuilder.build(ProgressBarBuilder.java:67)
        at io.titandata.titan.utils.ProgressTracker.trackWithBar(ProgressTracker.kt:41)
        at io.titandata.titan.utils.ProgressTracker.track(ProgressTracker.kt:52)
        at io.titandata.titan.providers.local.Install$1.invoke(Install.kt:18)
        at io.titandata.titan.providers.local.Install$1.invoke(Install.kt:12)
        at io.titandata.titan.providers.local.Install.install(Install.kt:22)
        at io.titandata.titan.providers.Local.install(Local.kt:137)
        at io.titandata.titan.commands.Install.run(Install.kt:28)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:139)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:215)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:212)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:230)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:253)
        at io.titandata.titan.Cli.main(Cli.kt:94)

Dec 24, 2019 4:43:52 AM org.jline.utils.Log logr
WARNING: Unable to retrieve infocmp for type dumb
java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at org.jline.utils.InputStreamReader.<init>(InputStreamReader.java:135)
        at org.jline.utils.InfoCmp.loadDefaultInfoCmp(InfoCmp.java:608)
        at org.jline.utils.InfoCmp.lambda$static$3(InfoCmp.java:619)
        at org.jline.utils.InfoCmp.getLoadedInfoCmp(InfoCmp.java:557)
        at org.jline.utils.InfoCmp.getInfoCmp(InfoCmp.java:545)
        at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:187)
        at org.jline.terminal.impl.DumbTerminal.<init>(DumbTerminal.java:88)
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:401)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:259)
        at me.tongfei.progressbar.ProgressThread.<init>(ProgressThread.java:56)
        at me.tongfei.progressbar.ProgressBar.<init>(ProgressBar.java:91)
        at me.tongfei.progressbar.ProgressBarBuilder.build(ProgressBarBuilder.java:67)
        at io.titandata.titan.utils.ProgressTracker.trackWithBar(ProgressTracker.kt:41)
        at io.titandata.titan.utils.ProgressTracker.track(ProgressTracker.kt:52)
        at io.titandata.titan.providers.local.Install$1.invoke(Install.kt:18)
        at io.titandata.titan.providers.local.Install$1.invoke(Install.kt:12)
        at io.titandata.titan.providers.local.Install.install(Install.kt:22)
        at io.titandata.titan.providers.Local.install(Local.kt:137)
        at io.titandata.titan.commands.Install.run(Install.kt:28)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:139)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:215)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:212)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:230)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:253)
        at io.titandata.titan.Cli.main(Cli.kt:94)

null
java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at org.jline.utils.InputStreamReader.<init>(InputStreamReader.java:135)
        at org.jline.utils.InfoCmp.loadDefaultInfoCmp(InfoCmp.java:608)
        at org.jline.utils.InfoCmp.lambda$static$3(InfoCmp.java:619)
        at org.jline.utils.InfoCmp.getLoadedInfoCmp(InfoCmp.java:557)
        at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:193)
        at org.jline.terminal.impl.DumbTerminal.<init>(DumbTerminal.java:88)
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:401)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:259)
        at me.tongfei.progressbar.ProgressThread.<init>(ProgressThread.java:56)
        at me.tongfei.progressbar.ProgressBar.<init>(ProgressBar.java:91)
        at me.tongfei.progressbar.ProgressBarBuilder.build(ProgressBarBuilder.java:67)
        at io.titandata.titan.utils.ProgressTracker.trackWithBar(ProgressTracker.kt:41)
        at io.titandata.titan.utils.ProgressTracker.track(ProgressTracker.kt:52)
        at io.titandata.titan.providers.local.Install$1.invoke(Install.kt:18)
        at io.titandata.titan.providers.local.Install$1.invoke(Install.kt:12)
        at io.titandata.titan.providers.local.Install.install(Install.kt:22)
        at io.titandata.titan.providers.Local.install(Local.kt:137)
        at io.titandata.titan.commands.Install.run(Install.kt:28)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:139)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:215)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:212)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:230)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:253)
        at io.titandata.titan.Cli.main(Cli.kt:94)
**root@DBForTitan:/home/ubuntu#** docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
**root@DBForTitan:/home/ubuntu#** docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

**Comment by Shawn-Yuan-byte** [comment]
I had the same problem when installing version 0.4.0

**Comment by robertericreeves** [comment]
+1

I was running GitHub Bash and ran into this error. SSH to EC2. Looks like a terminal issue as I switched to WLS bash and was able to get past it.

So, try switching to a terminal without color coding to see if that works.
